[tools]
bun = "latest"
deno = "2"
dotnet = "10"
node = "lts"
pnpm = "latest"
rust = { version = "latest", profile = "default", components = "rust-analyzer" }
cargo-binstall = "latest"
"aqua:astral-sh/uv" = "latest"
"aqua:aws/aws-cli" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:dandavison/delta" = "latest"
"aqua:jesseduffield/lazygit" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:rhysd/actionlint" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:suzuki-shunsuke/pinact" = "latest"
"aqua:x-motemen/ghq" = "latest"
"aqua:zellij-org/zellij" = "latest"
cocogitto = "latest"
"cargo:eza" = "latest"
"cargo:jscpd" = "latest"
difftastic = "latest"
flyctl = "latest"
ghalint = "latest"
github-cli = "latest"
"github:DeusData/codebase-memory-mcp" = "latest"
"github:tomasz-tomczyk/crit" = "latest"
hunk = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:@openai/codex" = "latest"
rtk = "latest"
sheldon = "latest"
shellcheck = "latest"
terraform = "latest"
yazi = "latest"
zizmor = "latest"

[settings]
idiomatic_version_file_enable_tools = []
experimental = true

[settings.python]
uv_venv_auto = true

[settings.npm]
package_manager = "pnpm"
